# permissions for end users to view apisixconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apisixconfiguration-viewer-role
rules:
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - apisixconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - apisixconfigurations/status
  verbs:
  - get
