# permissions for end users to view dataplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataplane-viewer-role
rules:
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - dataplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - dataplanes/status
  verbs:
  - get
