---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - apisixconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - apisixconfigurations/finalizers
  verbs:
  - update
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - apisixconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - controlplanes/finalizers
  verbs:
  - update
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - dataplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - dataplanes/finalizers
  verbs:
  - update
- apiGroups:
  - apisix-operator.apisix-operator.apisix.apache.org
  resources:
  - dataplanes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
